### ISSUE TITLE
Implement mdns reflector service

### ISSUE THREAD

**Issue by steersbob** [BrewBlox/brewblox-images#11]
## Context

Brewblox uses [Multicast DNS (mDNS)](https://en.wikipedia.org/wiki/Multicast_DNS) to discover Spark controllers. To complicate matters, the Spark services and the Spark controllers do not reside in the same network. Spark services are attached to a Docker bridge network, while the controllers are connected directly to the local network.

This can be resolved by enabling [Avahi Daemon reflection](https://www.brewblox.com/dev/decisions/20200822_avahi_reflection.html). This will cause mDNS packets to be forwarded between the bridge network and the local network (and vice versa).

Reflection is a valid solution for solving inter-network addressing because it is querying for IP addresses in the local network, which are reachable from the bridge network.

The problem with this solution is twofold:
- It enables reflection between all network interfaces on the host, and not just the local network (eg. wlan0) and the Brewblox bridge network.
- It requires editing host configuration settings. Where possible, we want to avoid this, as it will not be reverted when the user uninstalls Brewblox by removing the install directory.

## Desired features

- Targeted mDNS packet reflection between the bridge network as generated by docker-compose, and the host network interface connected to the home network.
- Configuration that is completely contained within the brewblox/ directory.
- Negligible memory/CPU footprint.
- Compatibility with all supported platforms: AMD64/ARM32/ARM64 Debian, and AMD64 Synology.

## Implementation

https://github.com/vfreex/mdns-reflector provides a straightforwards mDNS reflection service. It allows for reflection between specific networks, and it can be deployed as Docker container part of the docker-compose stack.
Its [Docker image](https://hub.docker.com/r/yuxzhu/mdns-reflector/tags) is built for all supported platforms.

It requires us to explicitly specify the reflected networks.
On the Docker side, we can [override the default network](https://docs.docker.com/compose/networking/#configure-the-default-network) to [set a fixed network name](https://docs.docker.com/network/network-tutorial-standalone/#use-user-defined-bridge-networks).
On the host side, we'll have to determine the relevant network(s) at startup. Typically, this is done using `ip link` and some grep magic.

## Problems

Initial prototyping was successful on Desktop and Pi environments, but ran into problems on Synology. The Docker network implementation by Synology is proprietary and differs from the "normal" implementation to the point that setting a custom network name disables the entire bridge network.

This is not impossible to remedy (we can autodetect the bridge network name if needed), but does complicate matters.

**Comment by Jonmccombs** [comment]
this would be a nice feature to add.

**Comment by steersbob** [comment]
It's a desired feature for multiple reasons, but has been put on the back burner after initial prototypes revealed configuration problems on Synology.
I updated the initial issue to document implementation details before I forget. We'll likely revisit this in the future, but it may take a while.

**Comment by steersbob** [comment]
This is implemented in https://github.com/BrewBlox/brewblox-ctl/pull/218. Avahi reflection is disabled by default, and a reflector service is enabled for each detected physical interface.
